services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  network-service:
    build:
      context: ./src
    container_name: my-network-service
    ports:
      - "5000:5000"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
