services:
  postgres:
    image: postgres:17.5
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  network-service:
    build:
      context: ./src
    container_name: my-network-service
    ports:
      - "5000:5000"

volumes:
  postgres_data:
